# Generated by Django 5.0.6 on 2024-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=255, unique=True)),
                ('email', models.EmailField(default='admin@gmail.com', max_length=254)),
                ('password', models.CharField(default='password123', max_length=255)),
            ],
        ),
    ]
