# Generated by Django 5.0.6 on 2024-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='profile',
            field=models.FileField(null=True, upload_to='user_profile/'),
        ),
    ]
