# Generated by Django 5.0.6 on 2024-09-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userregistration_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalimage',
            name='encryption_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='encryption_time_ist',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
