# Generated by Django 5.1.6 on 2025-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_uploadimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='encrypted_image',
            field=models.TextField(),
        ),
    ]
