# Generated by Django 5.1.6 on 2025-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_uploadimagemodel_encrypted_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='encrypted_image',
            field=models.BinaryField(null=True),
        ),
    ]
